name = 'Emend'
license = 'AGPL-3.0-or-later'
licenselink = 'https://github.com/haydenk/emend/blob/master/LICENSE'
description = 'A minimal, plain-CSS, CSP-friendly Hugo theme. Hard fork of Typo.'
homepage = 'https://github.com/haydenk/emend'
demosite = 'https://haydenk.github.io/emend/'
min_version = '0.158.0'

tags = ["blog", "minimal", "light", "dark", "responsive", "personal"]
features = ["table-of-contents", "taxonomies", "archive", "dark-mode", "no-third-party-requests"]

[author]
name = 'Hayden King'
homepage = 'https://www.haydenk.com/'

[original]
name = 'Typo'
author = 'Francesco Tomaselli'
homepage = 'https://github.com/tomfran/typo'
repo = 'https://github.com/tomfran/typo'
